# This fixes Emacs's TRAMP mode
# https://www.emacswiki.org/emacs/TrampMode (Tramp hangs #3)
if [[ "$TERM" == "dumb" ]]
then
    unsetopt zle
    PS1='$ '
    return
fi

export PATH=$HOME/.local/bin:$HOME/bin:/usr/local/bin:$PATH
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="minimal"
HYPHEN_INSENSITIVE="true"
HIST_STAMPS="yyyy-mm-dd"

plugins=(
    fast-syntax-highlighting
    pass
    fzf-zsh-plugin
    kubectl
)

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#586e75"

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8
export EDITOR='emacsclient -c'
export SSH_KEY_PATH="~/.ssh/rsa_id"
# https://www.gnupg.org/documentation/manuals/gnupg/Common-Problems.html
export GPG_TTY=$(tty)

export DOTFILES="$HOME/dotfiles"
export ZSH_DOTFILES="$DOTFILES/zsh"

alias ll='exa -lgumh --group-directories-first --color-scale'

source $ZSH_DOTFILES/python
source $ZSH_DOTFILES/gcp
source $ZSH_DOTFILES/k8s
source $ZSH_DOTFILES/rust
source $ZSH_DOTFILES/ms
source $ZSH_DOTFILES/datamole
